GET http://localhost:3000/bank-accounts

###

GET http://localhost:3000/bank-accounts/846291d4-3ce8-4720-8f36-febd5b87068b

###

POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
  "account_number": "1111-1",
  "owner_name": "John Doe"
}

###

GET http://localhost:3000/bank-accounts/846291d4-3ce8-4720-8f36-febd5b87068b/pix-keys

###

POST  http://localhost:3000/bank-accounts/846291d4-3ce8-4720-8f36-febd5b87068b/pix-keys
Content-Type: application/json

{
  "kind": "email",
  "key": "user@email.com"
}
